name: Deploy

on:
  workflow_dispatch:
  push:
    branches: [ dev ]
  workflow_run:
    workflows: [Build]
    types: [completed]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: [ self-hosted, linux, ARM64 ]
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v3

      - name: Download Package
        run: |
          PACKAGE=`./package.sh name`
          aws s3api get-object \
            --bucket release \
            --endpoint-url ${{ secrets.S3_ENDPOINT }} \
            --key release/${PACKAGE} \
            /opt/${PACKAGE}

      - name: Extract
        run: adr-extract /opt/germany-latest.osm.pbf /opt/adr/germany.adr

      - name: Restart Server
        run: sudo /bin/systemctl restart adr